# Generated by Django 3.2.7 on 2025-01-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_hall_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.FileField(upload_to=''),
        ),
    ]
