# Generated by Django 3.2.7 on 2025-01-24 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20250123_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.decoration'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.food'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='photography_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration_image',
            field=models.FileField(upload_to=''),
        ),
    ]
