# Generated by Django 3.2.7 on 2025-01-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20250124_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='customization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
