# Generated by Django 3.2.7 on 2025-01-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20250124_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='decoration_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
