# Generated by Django 3.2.7 on 2025-01-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20250124_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
